/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

import javax.swing.JOptionPane;
import ucr.ac.cr.sigereco.controlador.ControladorLogin;

/**
 *
 * @author XPC
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin(ControladorLogin controlador) {
        initComponents();
        panelBotones1.escuchar(controlador);
        panelLogin1.escuchar(controlador);
    }
    
    public PanelBotones getPanelBotones() {
        return panelBotones1;

    }

    public PanelLogin getPanelLogin() {
        return panelLogin1;

    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones1 = new ucr.ac.cr.sigereco.vista.PanelBotones();
        panelLogin1 = new ucr.ac.cr.sigereco.vista.PanelLogin();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
        getContentPane().add(panelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.sigereco.vista.PanelBotones panelBotones1;
    private ucr.ac.cr.sigereco.vista.PanelLogin panelLogin1;
    // End of variables declaration//GEN-END:variables
}
