/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

import ucr.ac.cr.sigereco.controlador.ControladorPrincipal;

/**
 *
 * @author Drexler Guzman
 */
public class FrameUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrameUsuario
     */
    public FrameUsuario() {
        initComponents();
        jMenuBarUsuario.add(jMenuIAyuda);
        jMenuBarUsuario.add(jMenuIUsuario);
        jMenuBarUsuario.add(jMenuICerrarSesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuIAyuda = new javax.swing.JMenuItem();
        jMenuICerrarSesion = new javax.swing.JMenuItem();
        jMenuIUsuario = new javax.swing.JMenuItem();
        panelConsulta1 = new ucr.ac.cr.sigereco.vista.PanelConsulta();
        panelTop101 = new ucr.ac.cr.sigereco.vista.PanelTop10();
        jMenuBarUsuario = new javax.swing.JMenuBar();
        jMenuExplorador = new javax.swing.JMenu();
        jMenuIRecetario = new javax.swing.JMenuItem();
        jMenuIFavoritas = new javax.swing.JMenuItem();

        jMenuIAyuda.setText("Ayuda");
        jMenuIAyuda.setFocusable(true);
        jMenuIAyuda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuIAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenuICerrarSesion.setText("Cerrar sesión");
        jMenuICerrarSesion.setActionCommand("Cerrar sesion");
        jMenuICerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuICerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenuIUsuario.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuExplorador.setText("Explorador");

        jMenuIRecetario.setText("Recetario");
        jMenuExplorador.add(jMenuIRecetario);

        jMenuIFavoritas.setText("Favoritas");
        jMenuExplorador.add(jMenuIFavoritas);

        jMenuBarUsuario.add(jMenuExplorador);

        setJMenuBar(jMenuBarUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTop101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTop101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(panelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameUsuario().setVisible(true);
//            }
//        });
//    }

    public void escuchar(ControladorPrincipal controladorPrincipal) {
        
        jMenuIAyuda.addActionListener(controladorPrincipal);
        jMenuICerrarSesion.addActionListener(controladorPrincipal);
        jMenuIFavoritas.addActionListener(controladorPrincipal);
        jMenuIRecetario.addActionListener(controladorPrincipal);
        
    }

    public void asignarUsuario(String usuario) {
        jMenuIUsuario.setText(usuario);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarUsuario;
    private javax.swing.JMenu jMenuExplorador;
    private javax.swing.JMenuItem jMenuIAyuda;
    private javax.swing.JMenuItem jMenuICerrarSesion;
    private javax.swing.JMenuItem jMenuIFavoritas;
    private javax.swing.JMenuItem jMenuIRecetario;
    private javax.swing.JMenuItem jMenuIUsuario;
    private ucr.ac.cr.sigereco.vista.PanelConsulta panelConsulta1;
    private ucr.ac.cr.sigereco.vista.PanelTop10 panelTop101;
    // End of variables declaration//GEN-END:variables
}
