/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

import javax.swing.JPanel;
import ucr.ac.cr.sigereco.controlador.ControladorPrincipal;
import ucr.ac.cr.sigereco.modelo.Usuario;

/**
 *
 * @author Drexler Guzman
 */
public class FrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    
    public FrameAdmin() {
        initComponents();
        jMenuBar.add(jMenuIAyuda);
        jMenuBar.add(jMenuINombreUsuario);
        jMenuBar.add(jMenuICerrarSesion);
        
    }

    public void escuchar(ControladorPrincipal controladorPrincipal){
    
        panelAdmin1.escuchar(controladorPrincipal);
        jMenuIAyuda.addActionListener(controladorPrincipal);
        jMenuICerrarSesion.addActionListener(controladorPrincipal);
        jMenuINombreUsuario.addActionListener(controladorPrincipal);
        jMenuIRecetario.addActionListener(controladorPrincipal);
        
    
    }
    
    public void asignarUsuario(String nombreUsuario){
    
        jMenuINombreUsuario.setText(nombreUsuario);
    
    }
    
    public PanelAdmin getPanelAdmin(){
        return panelAdmin1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuINombreUsuario = new javax.swing.JMenuItem();
        jMenuIAyuda = new javax.swing.JMenuItem();
        jMenuICerrarSesion = new javax.swing.JMenuItem();
        JMenuIConsulta = new javax.swing.JMenuItem();
        panelAdmin1 = new ucr.ac.cr.sigereco.vista.PanelAdmin();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuExplorador = new javax.swing.JMenu();
        jMenuIRecetario = new javax.swing.JMenuItem();

        jMenuINombreUsuario.setText("Usuario");
        jMenuINombreUsuario.setActionCommand("NombreUsuario");

        jMenuIAyuda.setText("Ayuda");
        jMenuIAyuda.setActionCommand("AyudaAdmin");

        jMenuICerrarSesion.setText("Cerrar sesion");

        JMenuIConsulta.setText("Consulta");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdmin1.setOpaque(false);
        getContentPane().add(panelAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 1280, 717));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recetario fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jMenuExplorador.setText("Explorador");

        jMenuIRecetario.setText("Recetario");
        jMenuExplorador.add(jMenuIRecetario);

        jMenuBar.add(jMenuExplorador);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuIConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuExplorador;
    private javax.swing.JMenuItem jMenuIAyuda;
    private javax.swing.JMenuItem jMenuICerrarSesion;
    private javax.swing.JMenuItem jMenuINombreUsuario;
    private javax.swing.JMenuItem jMenuIRecetario;
    private ucr.ac.cr.sigereco.vista.PanelAdmin panelAdmin1;
    // End of variables declaration//GEN-END:variables

}
