/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

import javax.swing.JOptionPane;
import ucr.ac.cr.sigereco.controlador.ControladorPrincipal;
import ucr.ac.cr.sigereco.controlador.ControladorUsuarios;

/**
 *
 * @author XPC
 */
public class FrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    public FrameRegistro() {
        initComponents();
        
    }
    
    public String getTxtNombre() {
        return panelRegistro1.getTxtNombre();
    }

    public void setTxtNombre(String apellido) {
        panelRegistro1.setTxtNombre(apellido);
    }

    public String getTxtApellido() {
        return panelRegistro1.getTxtApellido();
    }

    public void setTxtApellido(String apellido) {
        panelRegistro1.setTxtApellido(apellido);
    }

    public String getTxtCorreo() {
        return panelRegistro1.getTxtCorreo();
    }

    public void setTxtCorreo(String correo) {
        panelRegistro1.setTxtCorreo(correo);
    }

    public String getTxtNombreUsuario() {
        return panelRegistro1.getTxtNombreUsuario();
    }

    public void setTxtNombreUsuario(String nombreUsuario) {
        panelRegistro1.setTxtNombreUsuario(nombreUsuario);
    }

    public String getTxtPais() {
        return panelRegistro1.getTxtPais();
    }

    public void setTxtPais(String pais) {
        panelRegistro1.setTxtPais(pais);
    }
    
    public String getTxtContrasena() {
        return panelRegistro1.getTxtContrasena();
    }

    public void setTxtContrasena(String contrasena) {
        panelRegistro1.setTxtContrasena(contrasena);
    }
    
    public String getCboxTipo() {
        return panelRegistro1.getCboxTipo();
    }

    public void setCboxTipo(String jComboTipo) {
        panelRegistro1.setCboxTipo(jComboTipo);
    }
    
    public String getTxtID() {

        return panelRegistro1.getTxtID();

    }

    public void setTxtID(String ID) {

        panelRegistro1.setTxtID(ID);

    }
    
    public void limpiar(){
    
        panelRegistro1.limpiar();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro1 = new ucr.ac.cr.sigereco.vista.PanelRegistro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.sigereco.vista.PanelRegistro panelRegistro1;
    // End of variables declaration//GEN-END:variables

    public void escuchar(ControladorUsuarios controladorUsuarios) {
        panelRegistro1.escuchar(controladorUsuarios);
    }

    public void bloquearID() {
        panelRegistro1.bloquearID();
    }
    
    public void habilitarID() {
        panelRegistro1.habilitarID();
    }
}
