/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

/**
 *
 * @author Drexler Guzman
 */
public class FrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    public FrameAdmin() {
        initComponents();
    }
    
//    public void escuchar(ControladorPrincipal controladorPrincipal){
//    
//        panelAdmin1.escuchar();
//    
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin1 = new ucr.ac.cr.sigereco.vista.PanelAdmin();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuModUsu = new javax.swing.JMenu();
        jMenuModAdmin = new javax.swing.JMenu();
        jMenuNomUsu = new javax.swing.JMenu();
        jMenuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuAyuda.setText("Ayuda");
        jMenuBar.add(jMenuAyuda);

        jMenuModUsu.setText("Modo Usuario");
        jMenuBar.add(jMenuModUsu);

        jMenuModAdmin.setText("Modo Administrador");
        jMenuBar.add(jMenuModAdmin);

        jMenuNomUsu.setText("Nombre_Usuario");
        jMenuBar.add(jMenuNomUsu);

        jMenuCerrarSesion.setText("Cerrar sesion");
        jMenuBar.add(jMenuCerrarSesion);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCerrarSesion;
    private javax.swing.JMenu jMenuModAdmin;
    private javax.swing.JMenu jMenuModUsu;
    private javax.swing.JMenu jMenuNomUsu;
    private ucr.ac.cr.sigereco.vista.PanelAdmin panelAdmin1;
    // End of variables declaration//GEN-END:variables
}
