/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

import java.awt.Graphics;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import ucr.ac.cr.sigereco.controlador.ControladorPrincipal;


/**
 *
 * @author XPC
 */
public class PanelRecetario extends javax.swing.JPanel {

    /**
     * Creates new form PanelRecetario
     */
    private ImageIcon imagenComida;
    public PanelRecetario( ) {
        initComponents();
    }
    
    public void paint (Graphics g){
    
        super.paint(g);
        imagenComida.paintIcon(null, g, 500, 350);
    
    }

    public void setjLabelCategoria(String categoria) {
        jLabelCategoria.setText(categoria);
    }

    public void setjLabelCoccion(String coccion) {
        jLabelCoccion.setText(coccion);
    }

    public void setjLabelComple(String complejidad) {
        jLabelComple.setText(complejidad);
    }

    public void setjLabelDescripcion(String descripcion) {
        jLabelDescripcion1.setText(descripcion);
    }

    public void setjLabelImagen(String imagen) {
        imagenComida=new ImageIcon(imagen);
        //jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagen)));
    }

    public void setjLabelIngredientes(String Ingredientes) {
        jLabelIngredientes.setText(Ingredientes);
    }

    public void setjLabelNombre(String nombre) {
        jLabelNombre.setText(nombre);
    }

    public void setjLabelOcasion(String ocasion) {
        jLabelOcasion.setText(ocasion);
    }

    public void setjLabelPorciones(String porciones) {
        jLabelPorciones.setText(porciones);
    }

    public void setjLabelTiempoPrepa(String tiempoPreparacion) {
        jLabelTiempoPrepa.setText(tiempoPreparacion);
    }

    public void setjLabelPreparacion(String preparacion) {
        jLabelPreparacion.setText(preparacion);
    }

    public void setjLabelTotal(String total) {
        jLabelTotal.setText(total);
    }
    
    public void setjLabelDificultad(String dificultad){
    
        jLabelComple.setText(dificultad);
    
    }
    
    public void escuchar(ControladorPrincipal controladorPrincipal){
        btnAtras.addActionListener(controladorPrincipal);
        btnMeGusta.addActionListener(controladorPrincipal);
        btnAnterior.addActionListener(controladorPrincipal);
        btnSiguiente.addActionListener(controladorPrincipal);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTiempoPrepa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCoccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPorciones = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelDescripcion1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelIngredientes = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPreparacion = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelComple = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelOcasion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        btnMeGusta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(41, 111, 127));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setText("Recetario");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabelNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelNombre.setText("0");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Tiempo de preparacion:");

        jLabelTiempoPrepa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelTiempoPrepa.setText("0");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Cocción:");

        jLabelCoccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCoccion.setText("0");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Total:");

        jLabelTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelTotal.setText("0");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Porciones:");

        jLabelPorciones.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelPorciones.setText("0");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("Descripción:");

        jLabelDescripcion1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelDescripcion1.setText("Nada");
        jLabelDescripcion1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setText("Ingredientes:");

        jLabelIngredientes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelIngredientes.setText("0");
        jLabelIngredientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelIngredientes.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("Preparación:");

        jLabelPreparacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelPreparacion.setText("Nada");

        jLabelImagen.setText("imagen");

        btnSiguiente.setBackground(new java.awt.Color(41, 111, 127));
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");

        btnAnterior.setBackground(new java.awt.Color(41, 111, 127));
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Anterior");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(jLabelTiempoPrepa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(jLabelCoccion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPorciones, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAnterior)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiguiente))
                            .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2477, 2477, 2477))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNombre))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTiempoPrepa)
                    .addComponent(jLabel4)
                    .addComponent(jLabelCoccion)
                    .addComponent(jLabel5)
                    .addComponent(jLabelTotal))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelPorciones))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSiguiente)
                            .addComponent(btnAnterior)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(644, 644, 644)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9))
                    .addComponent(jLabelPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 720));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setText("Estadisticas");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setText("Complejidad:");

        jLabelComple.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelComple.setText("0");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setText("Ocasión:");

        jLabelOcasion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelOcasion.setText("0");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Categoria:");

        jLabelCategoria.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCategoria.setText("0");

        btnMeGusta.setBackground(new java.awt.Color(41, 111, 127));
        btnMeGusta.setForeground(new java.awt.Color(255, 255, 255));
        btnMeGusta.setText("Me gusta");
        btnMeGusta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeGustaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabelComple, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelOcasion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeGusta)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabelComple)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabelOcasion)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabelCategoria)
                .addGap(27, 27, 27)
                .addComponent(btnMeGusta))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 260, 390));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recetario Final_Mesa de trabajo 1.jpg"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -140, 1780, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeGustaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeGustaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMeGustaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnMeGusta;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCoccion;
    private javax.swing.JLabel jLabelComple;
    private javax.swing.JLabel jLabelDescripcion1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelIngredientes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelOcasion;
    private javax.swing.JLabel jLabelPorciones;
    private javax.swing.JLabel jLabelPreparacion;
    private javax.swing.JLabel jLabelTiempoPrepa;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
