/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sigereco.vista;

import ucr.ac.cr.sigereco.controlador.ControladorPrincipal;
import ucr.ac.cr.sigereco.controlador.ControladorUsuarios;

/**
 *
 * @author Drexler Guzman
 */
public class PanelInicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicioSesion
     */
    public PanelInicioSesion() {
        initComponents();
    }
    
    public String getTxtUsuario(){
    
        return txtUsuario.getText();
    
    }
    
    public String getTxtContrasena(){
    
        return txtContrasena.getText();
    
    }
    
    public void limpiar() {
        
        txtContrasena.setText("");
        txtUsuario.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        lblFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("Iniciar sesion");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 101, -1, -1));

        lblUsuario.setText("Usuario:");
        add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 138, -1, -1));
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 135, 145, -1));

        lblContrasena.setText("Contraseña:");
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 178, -1, -1));

        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.setActionCommand("IniciarSesionPanIS");
        add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.setActionCommand("AtrasPanIS");
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 175, 145, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicioSesion.jpg"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void escuchar(ControladorPrincipal controladorPrincipal) {
        
        btnAtras.addActionListener(controladorPrincipal);
        btnInicioSesion.addActionListener(controladorPrincipal);
    }

}
